apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: v1-nginx
  name: v1-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v1-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: v1-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: v1-nginx
  name: v1-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: v1-nginx 
status:
  loadBalancer: {}
